# Generated by Django 2.2.6 on 2019-11-18 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coche',
            fields=[
                ('n_bastidor', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=100)),
                ('anyo', models.IntegerField()),
                ('n_km', models.IntegerField()),
                ('combustible', models.CharField(max_length=100)),
                ('potencia', models.IntegerField()),
                ('precio', models.FloatField()),
                ('cambio', models.CharField(max_length=100)),
                ('consumo', models.FloatField()),
                ('comentario', models.CharField(max_length=1000)),
                ('fotoCoche', models.ImageField(default='ImagenesC/None/no-img.jpg', upload_to='imagenesC/')),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('cod_ciudad', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('nombre_Marca', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=1000)),
                ('fecha_creacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('correo', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('contrasenya', models.CharField(max_length=100)),
                ('coche', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appOutletCar.Coche')),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('nombre_Modelo', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=100)),
                ('traccion', models.IntegerField()),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOutletCar.Marca')),
            ],
        ),
        migrations.AddField(
            model_name='coche',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOutletCar.Lugar'),
        ),
        migrations.AddField(
            model_name='coche',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOutletCar.Modelo'),
        ),
    ]
